"""Event stream repository for temporal restore (BL-03).

Bounded, indexed reads against the SQLite audit journal.
All queries use parameterized SQL and respect volume limits.
No QGIS dependency.
"""
import sqlite3
from typing import List, Optional

from .audit_backend import AuditEvent
from .search_service import _row_to_event
from .restore_contracts import (
    RestoreCutoff, CutoffType, MAX_EVENTS_PER_RESTORE,
)
from .logger import flog, timed_op
from .sql_safety import assert_safe_fragment
from .sqlite_schema import AUDIT_EVENT_SELECT_SQL

_EVENT_COLUMNS = AUDIT_EVENT_SELECT_SQL


def fetch_entity_stream(
    conn: sqlite3.Connection,
    datasource_fp: str,
    entity_fp: str,
    limit: int = MAX_EVENTS_PER_RESTORE,
) -> List[AuditEvent]:
    """Fetch all events for a single entity, ordered by event_id ASC."""
    assert_safe_fragment(_EVENT_COLUMNS)
    # B608: _EVENT_COLUMNS is a module-level column whitelist; values via `?`.
    query = (
        "SELECT " + _EVENT_COLUMNS + " FROM audit_event"  # nosec B608
        " WHERE datasource_fingerprint = ? AND entity_fingerprint = ?"
        " ORDER BY event_id ASC LIMIT ?"
    )
    rows = conn.execute(query, (datasource_fp, entity_fp, limit)).fetchall()
    return [_row_to_event(r) for r in rows]


def fetch_events_after_cutoff(
    conn: sqlite3.Connection,
    datasource_fp: str,
    cutoff: RestoreCutoff,
    limit: int = MAX_EVENTS_PER_RESTORE,
    trace_id: str = "",
    include_traces: bool = False,
) -> List[AuditEvent]:
    """Fetch events after a cutoff, ordered for reverse replay (DESC).

    Returns events ordered by created_at DESC, event_id DESC so the caller can
    apply compensatory operations from most recent to oldest. event_id is
    only a tie-breaker because late pending-recovery inserts may hold an
    event_id that no longer reflects chronological order.

    When *include_traces* is True, restore_trace_events are included in the
    result. The rewind planner needs them to detect that an entity has
    already been restored by a previous rewind and to avoid re-applying
    a compensatory action (which causes feature accumulation).
    """
    with timed_op("fetch_events_after_cutoff", trace_id):
        where, params = _cutoff_where(datasource_fp, cutoff,
                                      include_traces=include_traces)
        if where is None:
            flog(
                f"fetch_events_after_cutoff: trace_id={trace_id} "
                f"datasource={datasource_fp} "
                f"cutoff_type={cutoff.cutoff_type.value} "
                f"inclusive={cutoff.inclusive} "
                f"include_traces={include_traces} "
                f"n_events=0 status=invalid_cutoff",
                "WARNING",
            )
            return []
        assert_safe_fragment(_EVENT_COLUMNS)
        assert_safe_fragment(where)
        # B608: fragments are constants / generated by _cutoff_where; values via `?`.
        query = (
            "SELECT " + _EVENT_COLUMNS + " FROM audit_event"  # nosec B608
            " WHERE " + where
            + " ORDER BY created_at DESC, event_id DESC LIMIT ?"
        )
        params.append(limit)
        events = [_row_to_event(r) for r in conn.execute(query, params).fetchall()]
        flog(
            f"fetch_events_after_cutoff: trace_id={trace_id} "
            f"datasource={datasource_fp} "
            f"cutoff_type={cutoff.cutoff_type.value} "
            f"inclusive={cutoff.inclusive} "
            f"include_traces={include_traces} "
            f"n_events={len(events)}",
            "INFO",
        )
        return events


def count_events_after_cutoff(
    conn: sqlite3.Connection,
    datasource_fp: str,
    cutoff: RestoreCutoff,
    trace_id: str = "",
    include_traces: bool = False,
) -> int:
    """Count events after a cutoff without loading them.

    When *include_traces* is True, restore_trace_events are counted as well.
    Must match the value used at fetch time so the count and the fetched
    list stay consistent.
    """
    with timed_op("count_events_after_cutoff", trace_id):
        where, params = _cutoff_where(datasource_fp, cutoff,
                                      include_traces=include_traces)
        if where is None:
            flog(
                f"count_events_after_cutoff: trace_id={trace_id} "
                f"datasource={datasource_fp} "
                f"cutoff_type={cutoff.cutoff_type.value} "
                f"inclusive={cutoff.inclusive} "
                f"include_traces={include_traces} "
                f"n_events=0 status=invalid_cutoff",
                "WARNING",
            )
            return 0
        assert_safe_fragment(where)
        # B608: `where` is generated by _cutoff_where; values via `params`.
        row = conn.execute(
            "SELECT COUNT(*) FROM audit_event WHERE " + where, params  # nosec B608
        ).fetchone()
        n_events = row[0] if row else 0
        flog(
            f"count_events_after_cutoff: trace_id={trace_id} "
            f"datasource={datasource_fp} "
            f"cutoff_type={cutoff.cutoff_type.value} "
            f"inclusive={cutoff.inclusive} "
            f"include_traces={include_traces} "
            f"n_events={n_events}",
            "INFO",
        )
        return n_events


def fetch_events_by_ids(
    conn: sqlite3.Connection,
    event_ids: List[int],
) -> List[AuditEvent]:
    """Fetch specific events by ID, ordered by event_id DESC."""
    if not event_ids:
        return []
    placeholders = ",".join("?" for _ in event_ids)
    assert_safe_fragment(_EVENT_COLUMNS)
    assert_safe_fragment(placeholders)
    # B608: `placeholders` is only `?,?,...`; event_ids bound via params.
    query = (
        "SELECT " + _EVENT_COLUMNS + " FROM audit_event"  # nosec B608
        " WHERE event_id IN (" + placeholders + ")"
        " ORDER BY event_id DESC"
    )
    return [_row_to_event(r) for r in conn.execute(query, event_ids).fetchall()]


def get_oldest_event_date(
    conn: sqlite3.Connection,
    datasource_fp: Optional[str] = None,
) -> Optional[str]:
    """Return created_at of the oldest event for a datasource (or all), or None."""
    if datasource_fp:
        row = conn.execute(
            "SELECT MIN(created_at) FROM audit_event"
            " WHERE datasource_fingerprint = ?",
            (datasource_fp,),
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT MIN(created_at) FROM audit_event",
        ).fetchone()
    if row and row[0]:
        return row[0]
    return None


def _cutoff_where(
    datasource_fp: Optional[str], cutoff: RestoreCutoff,
    include_traces: bool = False,
) -> tuple:
    """Build WHERE clause and params for a cutoff filter.

    When datasource_fp is None, the clause applies to all layers.
    When *include_traces* is True, restore_trace_events whose original
    event falls within the window are included (with invalidated_at IS NULL
    to exclude soft-deleted traces).
    Returns (where_clause, params) or (None, []) if cutoff type is invalid.
    """
    op = ">=" if cutoff.inclusive else ">"

    if cutoff.cutoff_type == CutoffType.BY_EVENT_ID:
        cutoff_col = "event_id"
    elif cutoff.cutoff_type == CutoffType.BY_DATE:
        cutoff_col = "created_at"
    else:
        flog(f"event_stream_repository: unknown cutoff type {cutoff.cutoff_type}", "WARNING")
        return None, []

    ds_cond = "datasource_fingerprint = ? AND " if datasource_fp else ""
    ds_params = [datasource_fp] if datasource_fp else []

    if not include_traces:
        clause = ds_cond + "restored_from_event_id IS NULL AND " + cutoff_col + " " + op + " ?"
        return clause, ds_params + [cutoff.value]

    user_clause = (
        "(restored_from_event_id IS NULL AND " + cutoff_col + " " + op + " ?)"
    )
    trace_clause = (
        "(restored_from_event_id IS NOT NULL"
        " AND invalidated_at IS NULL"
        " AND restored_from_event_id IN ("
        "SELECT event_id FROM audit_event WHERE "
        + ds_cond + cutoff_col + " " + op + " ?"
        + "))"
    )
    clause = ds_cond + "(" + user_clause + " OR " + trace_clause + ")"
    params = ds_params + [cutoff.value] + ds_params + [cutoff.value]
    return clause, params
